# Generated by Django 4.1.4 on 2023-01-21 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0005_tournament_confirmed_alter_tournament_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_score', models.IntegerField()),
                ('tie_score', models.IntegerField()),
                ('loose_score', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 13, 56, 23, 450373)),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Tournaments.scoring'),
        ),
    ]
