# Generated by Django 4.1.4 on 2023-01-21 13:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0006_scoring_alter_tournament_date_tournament_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoring',
            name='name',
            field=models.CharField(default='Rule', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 14, 1, 20, 873607)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Tournaments.scoring'),
        ),
    ]
