# Generated by Django 4.1.4 on 2023-01-21 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0008_alter_tournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 14, 19, 59, 362285)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 14, 19, 59, 362285)),
        ),
    ]
